repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: name-tests-test
-   repo: git@github.com:psf/black.git
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: git@github.com:pre-commit/mirrors-isort.git
    rev: v5.8.0
    hooks:
    -   id: isort
-   repo: git@github.com:PyCQA/flake8.git
    rev: '3.8.3'
    hooks:
    -   id: flake8
